### ISSUE TITLE
Double-clicking the xml label shows that the highlight color is too bright. 

### ISSUE THREAD

**Issue by eldicn** [antelle/intellij-xcode-dark-theme#1]
Double-clicking the xml label shows that the highlight color is too bright. 

![](https://gitee.com/plain-dev/oss/raw/master/upic_library/yiNMbD.png)

**Comment by antelle** [comment]
Hi!

Yeah, thanks for reporting, it's good that you submitted this issue because that's what I'm struggling with last couple of days. If you don't mind, I'll explain why it's like this and ask your opinion about possible solutions below.

What I wanted to recreate in IntelliJ is this effect that I actually find quite pretty:

![Screen Recording 2019-10-10 at 19 33 24 mov](https://user-images.githubusercontent.com/633557/66592368-2da5b600-eb95-11e9-90a9-e046cc291d5a.gif)

But if it's constantly highlighted and not just flashes like it does in XCode, the magic is lost and it starts being a bit annoying after a day or so.

Additionally I wanted to get this nice outline, which is drawn automatically only if you set the background color:

<img width="294" alt="Screen Shot 2019-10-10 at 19 36 56" src="https://user-images.githubusercontent.com/633557/66592484-66458f80-eb95-11e9-9029-34fab22ed3fc.png">

However this yellow highlighting creates more problems than it solves because it's not possible to customize it per language. Nor is it possible to override the text color of HTML/XML/... tags being highlighted, so it also creates these ugly artifacts, even more disappointing for eyes than your example:

<img width="347" alt="Screen Shot 2019-10-10 at 19 38 37" src="https://user-images.githubusercontent.com/633557/66592556-92f9a700-eb95-11e9-9d29-152405394480.png">

Well, now I'm thinking how to solve this... I discovered that it's possible to set the color transparency level in the plugin XML, which is not supported in the UI, so it can look something like this, but all of the variants are not good enough:

![variants](https://user-images.githubusercontent.com/633557/66594688-e7068a80-eb99-11e9-8912-db63a46cced7.png)

What's your opinion?

<details> 
  <summary>What I would choose</summary>
   The white one: these transparent yellowish backgrounds look somewhat dirty.
</details>

**Comment by eldicn** [comment]
@antelle 

> First of all, thank you for your reply, and thank you for making such a beautiful theme. 😄

Based on the solution you provided above, I personally think that the fourth "white background, white outline" is more beautiful because its color matches the overall style of the theme. However, the highlight color in Xcode is bright yellow, which is the opposite of the theme style of "Xcode". I don't know, what do you think?

**Comment by antelle** [comment]
Thanks, set it to white and uploaded a new version, it's waiting for JetBrains' approval and should be available soon.

I find it perfectly fine if it's different in a couple of things. XCode syntax highlighting by itself is not super-cool, so as I said in the [readme](https://github.com/antelle/intellij-xcode-dark-theme#xcode-dark-palette),
> This theme is not an exact copy, but rather an artist's impression of an editor theme with these colors.
