### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by deepmakadia1** [antelle/intellij-xcode-dark-theme#19]
This plugin in not showing xcode theme option in apperience in new Android Studio version (2020.3.1 Arctic Fox) even if the plugin is installed.

**Comment by antelle** [comment]
Hi! I've just tried this version and it works well for me:

<img width="1148" alt="Android Studio" src="https://user-images.githubusercontent.com/633557/127682885-ed7c215e-9a02-4883-bce4-2a1c40f2c677.png">

Not sure what we can do here because a theme plugin is just metadata, we don't have any code or something that affects the installation, so it's really on the IDE to make it work. Maybe uninstalling / installing will help.

**Comment by deepmakadia1** [comment]
@antelle I tried uninstalling / installing bur still not working (btw I'm trying in windows 10)

**Comment by lzh77** [comment]
The same issue, and my platform is windows 10.
I tried re-install this plugin, restart my PC, and not work.
I found this plugin in file `C:\Users\user\AppData\Roaming\Google\AndroidStudio2020.3\plugins\brokenPlugins.json` like this:
``` json
{
        "id": "net.antelle.intellij-xcode-dark-theme",
        "version": "1.0",
        "since": "191.0",
        "until": "",
        "originalSince": "173.0",
        "originalUntil": null
}
```
It seems that Jetbrains mantains a plugin list, and you can ask Jetbrains for help.

**Comment by antelle** [comment]
What about other themes?

**Comment by deepmakadia1** [comment]
I installed so many thems but none of them seems to be working. And I hate the default dracula one.

**Comment by antelle** [comment]
Ok, thank you for the confirmation, then it's for sure not our issue.

**Comment by nikunjparadva** [comment]
## Here is the Solution
https://stackoverflow.com/a/68599712/5773037
