### ISSUE TITLE
1.2.0 No longer Tint properly Kotlin syntax in Android Studio

### ISSUE THREAD

**Issue by armandoangulov** [antelle/intellij-xcode-dark-theme#6]
I just upload to 1.2.0 and the Kotlin syntax no longer using the Xcode Dark palette. I did try reinstalling but no luck.
Look like that tinted some elements of the UI but the Kotlin syntax still using the default android color scheme.
Was working good with 1.1.1.

Android Studio 4.2.
Haven't tried with Intellij 2020.2 yet.

**Comment by antelle** [comment]
Hi! Let's see what happens in IntelliJ for you. It works well for me with Kotlin. The only related change that I see in v1.2.0, is https://github.com/antelle/intellij-xcode-dark-theme/commit/1b652bd2b1c5c74b6934c4455b81e0441efc4926#diff-471c6dfce4765a8eb01c0e1e4df64cfdL231, but it shouldn't break it. Here's a version with this change reverted, what happens if you install it?
[intellij-xcode-dark-theme.jar.zip](https://github.com/antelle/intellij-xcode-dark-theme/files/5109723/intellij-xcode-dark-theme.jar.zip)

**Comment by armandoangulov** [comment]
Hi! Sorry for the late replay.

I tried reinstalling all, deleted preferences, etc. And downloaded AndroidStudio 4.2 Preview again.
I got the same result installing 1.2.0 from the Plugins/Marketplace and with the *.jar you attached.

Since I still have installed 1.1.1 on Intellij. I copied that jar and installed manually to AndroidStudio, now is working like before.
I'm not sure why it's not working with 1.2.0.

****
MacOS BigSur Beta 5
AndroidStudio 4.2 Preview Canary 7

**Comment by antelle** [comment]
Weird, I don't understand how it's possible. I'll try to download android studio to check what happens for me.

**Comment by peytonshetler** [comment]
Weird.  The text tinting isn't working for me either.

**Comment by antelle** [comment]
@peytonshetler with the same setup, or in intellij idea?

**Comment by peytonshetler** [comment]
@antelle Hey sorry, I just got some stuff figured out on it sort of.  I'm new to Android.  It didn't work for me on Android Studio 4.0.2 (multiple jar versions), but when I downloaded the Android Studio 4.1 Preview, the jar I had (1.1.1) did work.  Haven't tried 1.2.0.

**Comment by antelle** [comment]
I finally installed Android studio and figured it out, the fix is waiting for JetBrains' approval.

**Comment by antelle** [comment]
The update is published
